-- MySQL Script generated by MySQL Workbench
-- Mon Dec  5 13:35:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema users_base
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `users_base`;

-- -----------------------------------------------------
-- Schema users_base
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `users_base` DEFAULT CHARACTER SET utf8;
USE `users_base`;

-- -----------------------------------------------------
-- Table `users_base`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users_base`.`status`;

CREATE TABLE IF NOT EXISTS `users_base`.`status`
(
    `id`          INT         NOT NULL AUTO_INCREMENT,
    `status_name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users_base`.`gender`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users_base`.`gender`;

CREATE TABLE IF NOT EXISTS `users_base`.`gender`
(
    `id`          INT         NOT NULL AUTO_INCREMENT,
    `gender_name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users_base`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users_base`.`users`;

CREATE TABLE IF NOT EXISTS `users_base`.`users`
(
    `id`        INT         NOT NULL AUTO_INCREMENT,
    `email`     VARCHAR(45) NOT NULL,
    `name`      VARCHAR(45) NOT NULL,
    `gender_id` INT         NOT NULL,
    `status_id` INT         NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_gender_idx` (`gender_id` ASC) VISIBLE,
    INDEX `fk_status_idx` (`status_id` ASC) VISIBLE,
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
    CONSTRAINT `fk_gender`
        FOREIGN KEY (`gender_id`)
            REFERENCES `users_base`.`gender` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_status`
        FOREIGN KEY (`status_id`)
            REFERENCES `users_base`.`status` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `users_base`.`status`
-- -----------------------------------------------------
START TRANSACTION;
USE `users_base`;
INSERT INTO `users_base`.`status` (`id`, `status_name`)
VALUES (1, 'Active');
INSERT INTO `users_base`.`status` (`id`, `status_name`)
VALUES (2, 'Inactine');

COMMIT;


-- -----------------------------------------------------
-- Data for table `users_base`.`gender`
-- -----------------------------------------------------
START TRANSACTION;
USE `users_base`;
INSERT INTO `users_base`.`gender` (`id`, `gender_name`)
VALUES (1, 'Male');
INSERT INTO `users_base`.`gender` (`id`, `gender_name`)
VALUES (2, 'Female');

COMMIT;

